"""Regenerate docs/ALL_CODE.md from all source files in this repo.

Walks src/, notebooks/, and scripts/ for .py and .ipynb files and embeds
each into a single markdown file at docs/ALL_CODE.md. Intended as a
one-file read for an advisor / reviewer who wants to see all the code
at once without navigating the tree.

Re-run after any code change:
    python scripts/build_all_code.py

The output file is committed to the repository. The regenerator script
includes itself in the output so the build process is transparent.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "ALL_CODE.md"

SCAN_DIRS = ["src", "notebooks", "scripts"]
SCAN_EXTS = (".py", ".ipynb")
SKIP_DIR_NAMES = {"__pycache__", ".ipynb_checkpoints"}


def collect_files() -> list[Path]:
    files: list[Path] = []
    for d in SCAN_DIRS:
        root = ROOT / d
        if not root.exists():
            continue
        for ext in SCAN_EXTS:
            for p in root.rglob(f"*{ext}"):
                if any(part in SKIP_DIR_NAMES for part in p.parts):
                    continue
                files.append(p)
    return sorted(files, key=lambda p: p.relative_to(ROOT).as_posix())


def render_python(path: Path) -> str:
    body = path.read_text(encoding="utf-8")
    rel = path.relative_to(ROOT).as_posix()
    return f"## `{rel}`\n\n```python\n{body}\n```\n\n"


def render_notebook(path: Path) -> str:
    nb = json.loads(path.read_text(encoding="utf-8"))
    rel = path.relative_to(ROOT).as_posix()
    parts = [f"## `{rel}`\n"]
    for i, cell in enumerate(nb.get("cells", []), start=1):
        ctype = cell.get("cell_type", "unknown")
        source = "".join(cell.get("source", []))
        if ctype == "code":
            parts.append(f"\n### Cell {i} (code)\n\n```python\n{source}\n```\n")
        elif ctype == "markdown":
            parts.append(f"\n### Cell {i} (markdown)\n\n{source}\n")
        else:
            parts.append(f"\n### Cell {i} ({ctype})\n\n```\n{source}\n```\n")
    parts.append("\n")
    return "".join(parts)


def main() -> int:
    files = collect_files()

    header = (
        "# All Code — Vietnam FMCG Tet Effect\n\n"
        "Single-file aggregation of every source file in the repository "
        "(`src/`, `notebooks/`, `scripts/`).\n"
        "Intended for advisors / reviewers who want to read all the code "
        "in one place without navigating the tree.\n\n"
        "**Auto-generated** — do not edit this file by hand. "
        "Regenerate with `python scripts/build_all_code.py` after any code change.\n\n"
        "---\n\n"
    )

    if not files:
        body = "_No source files found in `src/`, `notebooks/`, or `scripts/` yet._\n"
    else:
        rendered: list[str] = []
        for f in files:
            if f.suffix == ".py":
                rendered.append(render_python(f))
            elif f.suffix == ".ipynb":
                rendered.append(render_notebook(f))
        body = "".join(rendered)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + body, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(files)} source file(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
